### ISSUE TITLE
Sivu 11-4: Haku binääripuusta esimerkki

### ISSUE THREAD

**Issue by ljleppan** [rage/python-s20#157]
Sivulla 11-4 on esimerkki funktiosta joka hakee alkiota järjestetystä binääripuusta:
```python
def etsi_alkio(juuri: Alkio, arvo):
    if arvo == juuri.arvo:
        return True

    if arvo > juuri.arvo:
        return etsi_alkio(juuri.oikea_lapsi, arvo)

    return etsi_alkio(juuri.vasen_lapsi, arvo)
```

Tämä esimerkki ei kuitenkaan toimi, vaan esimerkiksi koodin
```python
from typing import NamedTuple, Optional

class Alkio(NamedTuple):
    arvo: int
    vasen_lapsi: Optional['Alkio'] = None
    oikea_lapsi: Optional['Alkio'] = None


puu = Alkio(
    10,
    Alkio(
        6,
        Alkio(4),
        Alkio(8)
    ),
    Alkio(
        18,
        Alkio(15),
        Alkio(21)
    )
)

def etsi_alkio(juuri: Alkio, arvo):
    if arvo == juuri.arvo:
        return True

    if arvo > juuri.arvo:
        return etsi_alkio(juuri.oikea_lapsi, arvo)

    return etsi_alkio(juuri.vasen_lapsi, arvo)

print(etsi_alkio(puu, 7))
```
suorittaminen antaa poikkeuksen
```
Traceback (most recent call last):
  File "<snip>", line 32, in <module>
    print(etsi_alkio(puu, 7))
  File "<snip>", line 30, in etsi_alkio
    return etsi_alkio(juuri.vasen_lapsi, arvo)
  File "<snip>", line 28, in etsi_alkio
    return etsi_alkio(juuri.oikea_lapsi, arvo)
  File "<snip>", line 30, in etsi_alkio
    return etsi_alkio(juuri.vasen_lapsi, arvo)
  File "<snip>", line 24, in etsi_alkio
    if arvo == juuri.arvo:
AttributeError: 'NoneType' object has no attribute 'arvo'
```

Ongelma korjaantuu esimerkiksi seuraavalla muokkauksella:
```python
def etsi_alkio(juuri: Alkio, arvo):
    if arvo == juuri.arvo:
        return True

    if arvo > juuri.arvo:
        # Etsittävän arvon täytyy olla oikeanpuoleisessa alipuussa
        if juuri.oikea_lapsi is not None: 
            return etsi_alkio(juuri.oikea_lapsi, arvo)
        else:
            # Mutta oikeanpuoleista alipuuta ei ole olemassa, joten etsittävä arvo ei ole puussa
            return False
    else:
        # Etsittävän arvon täytyy olla vasemmanpuoleisessa alipuussa
        if juuri.vasen_lapsi is not None:
            return etsi_alkio(juuri.vasen_lapsi, arvo)
        else:
            # Mutta vasemmanpuoleista alipuuta ei ole olemassa, joten etsittävä arvo ei ole puussa
            return False
```

**Comment by pllk** [comment]
Kiitos! Kokeilin korjata vähän pienemmällä muutoksella, toimiikohan nyt?
